#
#,------.        ,--.                   ,--.          ,---.
#|  .--. ',--.--.`--',--.  ,--.,--,--.,-'  '-. ,---. '   .-'  ,---. ,--.--.,--.  ,--.,---. ,--.--.
#|  '--' ||  .--',--. \  `'  /' ,-.  |'-.  .-'| .-. :`.  `-. | .-. :|  .--' \  `'  /| .-. :|  .--'
#|  | --' |  |   |  |  \    / \ '-'  |  |  |  \   --..-'    |\   --.|  |     \    / \   --.|  |
#`--'     `--'   `--'   `--'   `--`--'  `--'   `----'`-----'  `----'`--'      `--'   `----'`--'
#Coded by @FlxwDNS
#Please read the wiki before changing: -

# MySQL is in sql.json

# Server
domains:
    - "sympta.de"
    - "example.de"

