#
#,------.        ,--.                   ,--.          ,---.
#|  .--. ',--.--.`--',--.  ,--.,--,--.,-'  '-. ,---. '   .-'  ,---. ,--.--.,--.  ,--.,---. ,--.--.
#|  '--' ||  .--',--. \  `'  /' ,-.  |'-.  .-'| .-. :`.  `-. | .-. :|  .--' \  `'  /| .-. :|  .--'
#|  | --' |  |   |  |  \    / \ '-'  |  |  |  \   --..-'    |\   --.|  |     \    / \   --.|  |
#`--'     `--'   `--'   `--'   `--`--'  `--'   `----'`-----'  `----'`--'      `--'   `----'`--'
#Coded by @FlxwDNS
#Please read the wiki before changing: -

# MySQL is in sql.json

# cloudnetv3, cloudnetv4, simplecloud
cloud-handler: "simplecloud"

# Server
domains:
    - "sympta.de"
    - "example.de"

# Plugins (define spigotmc id or direct link)
# if you provide spigotmc, the plugin will be downloaded from spigotmc with the latest version
plugins:
    every:
        - UniversalTeleportAnchor:
            - "COMPASS"                                               # <--- Material
            - "118462"                                                # <--- SpigotMC ID or direct link
            - "Erstelle Anker um dich in der Welt zu teleportieren."  # <--- Description
        - FastAsyncWorldEdit:
            - "WOODEN_AXE"
            - "https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/artifacts/FastAsyncWorldEdit-Bukkit-2.11.1-SNAPSHOT-865.jar"
            - "§7Willst du schnell und effizient bauen?\nDann ist FastAsyncWorldEdit genau das richtige für dich!"
        - RockPaperScissors:
            - "PAPER"
            - "118164"
            - "§7Lust gegen andere Spieler zu verlieren?\n§7Spiele doch mal Stein, Schere, Papier!"
    games:
        - SkyWarsReloaded:
            - "DIAMOND_SWORD"
            # If you are using spigotmc this is the id:
            # https://www.spigotmc.org/resources/skywarsreloaded-updated-recoded-1-20-2-support-new-features-supports-all-mc-versions.69436 <-------
            - "69436"
            - "Erstelle deine eigenen Epischen Luft schlachten."
