name: PrivateServer
main: dev.flxwdns.privateserver.PrivateServer
version: 1.0
api-version: "1.20"
author: FlxwDNS
description: A advanced privateserver system.
commands:
  privateserver:
    aliases: [ps]
    permission: privateserver.command